#!/usr/bin/env bash

# -- add the fabric system user
if id -u bbfabric >/dev/null 2>&1; then
        echo "The bbfabric user already exists. No need to create it."
else
        adduser --system bbfabric
fi

# -- create the fabric directory
chown -R bbfabric /var/log/bigboards
chmod -R 655 /var/log/bigboards

# -- change the rights to the bigboards directory
chown bbfabric -R /usr/share/bigboards-fabric

if [ ! -e "/usr/local/bin/bower" ];
then
    npm install bower -g
fi

pushd /usr/share/bigboards-fabric/code
    # -- remove the old modules
    [ -e npm_modules ] && rm -rf npm_modules
    [ -e node_modules ] && rm -rf node_modules

    # -- install the nodejs api dependencies
    sudo -u bbfabric npm install
popd

pushd /usr/share/bigboards-fabric/code/ui
    # -- remove the old modules
    rm -rf bower_components

    # -- make sure bower installs all dependencies
    sudo -u bbfabric bower install --config.interactive=false
popd