- hosts: host
  sudo: yes
  tasks:
    - name: get a list of available lxc containers
      shell: lxc-ls
      register: lxc_containers

    - name: be sure the lxc bb-template container is removed
      shell: lxc-destroy -f -n {{item}} removes=/var/lib/lxc/{{item}}
      ignore_errors: yes
      with_items: lxc_containers.stdout_lines

    - name: remove the deprecated hex facts
      file:
        path: '/etc/ansible/facts.d/hex.fact'
        state: 'absent'

    - file:
        path: "/data/{{ item }}"
        state: "absent"
      with_lines: find /data/ ! -readable -prune -type f -printf "%P\n"

- hosts: localhost
  sudo: yes
  tasks:
    - name: remove all current tints from the hex
      file:
        path: "/opt/bb/tints.d/{{item}}"
        state: "absent"
      with_items:
        - "stack"
        - "dataset"
        - "tutor"
